### PR TITLE
Implement List View

### PR DESCRIPTION
**Pull request by victoriaklo**
Testing out list view for issue #7

### CODE REVIEW

**Comment by victoriaklo** [comment]
Looking for feedback on approach: 


First pass at adding Event List view:
- Hard-coded start date and end date from event search form, and looping through to create dateMap object where date is the key, and the value is a list of events for that corresponding month.
- Then pull the list of events from the backend, loop through the list and add the values into the dateMap object.
- Need to find a way to access inputs from the events search form.

Pending questions: 
- What will the data look like/ how is it going to be processed in the backend? 
-  How should the event display if there is an event that occurs over multiple months? 
- Pagination, should we consider breaking them up into pages to offload the server? 
- The design shows events from May 2022 but the search event param start date is June, should previous events still display?

**Comment by reshamas** [comment]
@victoriaklo 
> Pending questions:
> 
> * What will the data look like/ how is it going to be processed in the backend?
> * How should the event display if there is an event that occurs over multiple months?
I don't think we have had events that are over multiple months.  Is there an example of some?

> * Pagination, should we consider breaking them up into pages to offload the server?
> * The design shows events from May 2022 but the search event param start date is June, should previous events still display?
The reason for this discrepancy is because the website was designed in May and we just started adding the events.  
If we do a search using previous dates, then they should show. It's good for testing.

**Comment by victoriaklo** [comment]
@reshamas 

Thanks for the quick reply and the follow-up. Apologies, these questions were meant for Joe to confirm the setup and design for the page. Joe and I met, so I have a better understanding of the implementation and updated designs. Thanks for your help, really appreciate it!

**Comment by jtorreggiani** [comment]
@victoriaklo, I tweaked the implementation here and add rough styles for the list view. Let's discuss with the other RAs during our next pairing session to go over how I used data structures here to handle the grouping by month logic. Merging to keep clear out the PR queue.

**Pull request merged**
