### PR TITLE
Move sponsor logos

### PR DESCRIPTION
**Pull request by SangamSwadiK**
## Ticket Description
**Issue**: #300   (**move the dark/light logos for CZI and DO should be in the sponsors folder**)

## Description of Changes
Move the CZI an digitalocean logos into  `src/assets/sponsors`
 and fix the imports in `src/components/elements/sponsors.jsx`

## Before and After for UI Updates
N/A

Before:
N/A

After:
N/A

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

Tagging @reshamas

### CODE REVIEW

**Review by Rohanfizz — APPROVED** [review]
LGTM✅

**Comment by reshamas** [comment]
@SangamSwadiK @Rohanfizz 
Should we have before & after screenshots to ensure that changes don't break anything?

**Comment by reshamas** [comment]
> > @SangamSwadiK @Rohanfizz Should we have before & after screenshots to ensure that changes don't break anything?
> 
> Hi @reshamas I couldn't find a way to preview the changes done by the PR similar to Netlify preview on the website.

@SangamSwadiK 
If you want to try setting up your working environment.  Instructions here:
https://github.com/data-umbrella/event-board-web/blob/main/CONTRIBUTING.md

My environment (to build and preview locally) was working a couple of months ago.  Currently, I can't seem to upgrade to latest version of node.

**Comment by Rohanfizz** [comment]
> @jtorreggiani @Rohanfizz Hi, can I resolve the conflicts (use my changes over main) and merge commit them ? Please let me know.
> 
> Thanks !

Yes you can do that @SangamSwadiK 😃

**Comment by Rohanfizz** [comment]
You can Merge the Pull request @SangamSwadiK LGTM✅

**Pull request merged**
