### PR TITLE
Implement Contact Page Design

### PR DESCRIPTION
**Pull request by victoriaklo**
[Work In Progress] Pair Programming with Yoline to build out the contact page. 
This PR is for issue Implement contact page #11

### CODE REVIEW

**Comment by victoriaklo** [comment]
Implement contact page #11

**Comment by victoriaklo** [comment]
Tasks to complete:
- implement tests 
- format the email and topic questions to be on the same line
- verify the link for the code of conduct

**Comment by victoriaklo** [comment]
Tasks still in progress:
- update styles to Email and Topic fields are on one line
- add multiple lines for Message text area
- Wire up the backend and API requests for Contact Form

**Review by jtorreggiani — APPROVED** [review]
@YolineB and @victoriaklo this code is looking good to me! We will want to add more tests and write it up with the backend API. To keep things moving along and avoid branches becoming stale I am going to merge this in and do the work to wire up the form in a separate PR. Excited to see all these PRs getting merged and deployed! 🚀

**Comment by jtorreggiani** [comment]
@victoriaklo, thank you for creating this task list! I am going to create issues to follow up on these implementation requirements. Since the app is not being used in production yet, we can merge this code without working about functionality or design polish missing. Once we release to production we will have to be more careful releasing partially complete features.

> Tasks to complete:
> 
> * [x]  implement tests
> * [ ]  format the email and topic questions to be on the same line
> * [ ]  verify the link for the code of conduct
> * [ ]  add multiple lines for Message text area
> * [ ]  Wire up the backend and API requests for Contact Form

**Pull request merged**
