### PR TITLE
Added the Google Open Source sponsor logo

### PR DESCRIPTION
**Pull request by BerylKanali**
## Ticket Description
Towards https://github.com/data-umbrella/event-board-web/issues/288

## Description of Changes
Created a new folder called sponsors that contains the different versions of the Google logo.
Added the multi color Google  logo to the sponsors page.

## Before and After for UI Updates
<-- You should have 2 images minimum, for desktop, 4 for mobile and desktop combined -->

Before:

Before

After:

After2

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

### CODE REVIEW

**Review by jtorreggiani — APPROVED** [review]
LGTM ✅

**Comment by jtorreggiani** [comment]
Thank you for opening this pull request @BerylKanali! Overall this looking good. I think we may need to adjust the css to align the labels. We are happy to pair with you on it or hop in to help.

**Comment by Rohanfizz** [comment]
> Thank you for opening this pull request @BerylKanali! Overall this looking good. I think we may need to adjust the css to align the labels. We are happy to pair with you on it or hop in to help.

I can fix the alignments once the PR is merged✅

**Comment by reshamas** [comment]
@Rohanfizz
Great, if you could take this up, that would be great!  Thanks.

**Pull request merged**
