### PR TITLE
Fixes Register Button on Event Page.

### PR DESCRIPTION
**Pull request by Rohanfizz**
## PR Overview

@jtorreggiani Please review this as I can't test with dummy backend.

#### Type of contribution
- [x] Code
- [ ] Documentation

#### Reference: Issue or Pull Request (PR)
- [x] Towards #342 [this will keep reference issue or PR open]  <=== _When in doubt, pick this one._
- [ ] Fixes #xxx. See also #xxx.   [this will close the referenced issue or PR]
- [ ] Resolves #xxx, #xxx [for multiple issues, this will close them]

## Ticket Description
#342 

## Description of Changes
Enclosed div tag inside anchor tag.
## Before and After for UI Updates
No UI changes.

## For PR Reviewer
- [ ] Does this file change the yarn.lock, package.json or package-lock.json file? If so, why?
- [ ] If this pr contains mobile and desktop changes, did you test on IphoneXr and desktop views?
- [ ] Does this file match the related tickets linked figma file, or does it pass the visual smell test?
- [ ] If this file contains javascript, does the javascript pass the smell test?
- [ ] If you don't feel super confident in your review, did you assign someone more senior to double check?

### CODE REVIEW

**Comment by reshamas** [comment]
Hi @Rohanfizz 
Thanks for this PR. For "342" in the Ticket description, 
1. can you check the box "Towards xxx"?
2. select "Code contribution"?

If the PR template is not clear, please let @SangamSwadiK and I know, we can update it.

**Comment by reshamas** [comment]
@Rohanfizz 
Where it says "Towards #xxx", can you replace it with "Towards #342"?

I wonder if we should remove the "Ticket Description" section all together.

**Comment by reshamas** [comment]
@SangamSwadiK 
Another option, only have "Towards #xxx".
Then, we can manually close the issue. This way, it links the PR to the issue.
And it is not too much for a contributor to read.

I thought our template would make it easier for contributors, but it may be complicating things. too much text there.

**Comment by jtorreggiani** [comment]
@Rohanfizz, since this got stale and the tests were breaking I pushed up fixes to unblock this. Let's sync up on some of the other open tickets.

**Review by jtorreggiani — APPROVED** [review]

**Pull request merged**
