### PR TITLE
add links to logos (DU & SPEC)

### PR DESCRIPTION
**Pull request by reshamas**
Towards #111 

@jtorreggiani I'm giving this a try!

### CODE REVIEW

**Comment by jtorreggiani** [comment]
@reshamas, it looks like CI is failing due to a linter error. Also, I think you have the link and name params swapped. Also, I added you as a contributor to the repository which means you can clone the repository directly and open pull requests directly against the repository versus the fork. It also makes it easier for us to pull down your changes to test and make fixes when needed.

**Comment by jtorreggiani** [comment]
@reshamas, since this branch was a fork we had trouble pulling this down and it became stale, so we ran into a merge conflict. I merged the conflict but only the copy changes worked with the merge. This was a good first stab and add the links here. I forgot this was set up with the list of sections which made this task a little more complex. I think the list of orgs is a bit of overcall for this section. I will make an issue to simplify the implementation of this page.

**Review by jtorreggiani — APPROVED** [review]
LGTM ✅

**Comment by reshamas** [comment]
@jtorreggiani We lost the links to the collective which I added in the code.

**Comment by reshamas** [comment]
@jtorreggiani I also added the links to the logos, which are now gone.

**Pull request merged**
